### ISSUE TITLE
HANDBOOK: Clarify donations page

### ISSUE THREAD

**Issue by stevespringett** [OWASP/www-committee-project#57]
Donations can be in the form of code (or entire projects). Project donations may be accepted by an existing OWASP project or form the basis of a new OWASP project. Currently, the donations page assumes monetary. The handbook needs to provide clarity around different types of donations.

**Comment by psiinon** [comment]
Not just code. Also:

- Documentation (inc videos)
- Quid-pro-quo - eg [WebSwing in ZAP](https://www.zaproxy.org/blog/2021-02-03-run-zap-without-java-using-docker-and-webswing/)
- Marketting maybe (although that could come with strings attached;)
-

**Comment by hblankenship** [comment]
That is listed under sponsorship: Sponsorship is generally considered material funds or contributions (development work, resources, meeting space, etc) 

Should it also be under donation?

**Comment by hblankenship** [comment]
Assuming that it being listed under sponsorship is sufficient unless otherwise indicated.
