### ISSUE TITLE
HANDBOOK: Clarify code and tool projects

### ISSUE THREAD

**Issue by stevespringett** [OWASP/www-committee-project#64]
There isn't enough clarity between code projects and tool projects. When does a code project become a tool project? I have no idea.

**Comment by hblankenship** [comment]
Tools are things that do a job and Code is a library/framework project that can be used to support other code/tools. Anyone have anything better? Is there a reason to specify a difference between tool and 'code'...it's all code. :D

**Comment by psiinon** [comment]
How does the distinction help us or people who use our projects?
Some tools (like ZAP) will provide both executables and libraries 😉 
Unless someone can justify it, I vote for dropping the distinction.

**Comment by hblankenship** [comment]
This was done.
